default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: picart
  username: picart
  password: picart

development:
  <<: *default
  database: picart_development
  username: picart
  password: picart

test: &test
  <<: *default
  database: picart_test
  username: picart
  password: picart


cucumber:
  <<: *test
